name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run on iOS Simulator iPhone 11 Pro
      run: xcodebuild clean test -target NettinTests -scheme Nettin -destination "platform=iOS Simulator,name=iPhone 11 Pro"
    - name: Run on macOS
      run: xcodebuild clean test -target NettinTests -scheme Nettin -destination "platform=macOS"
